@host = http://localhost:3000

### Read All Users
GET {{host}}/users/all

### 
GET {{host}}/users/all
# GET {{urlBase}}/products/importAll

###
GET {{host}}/form/parade-with-us

# Rotas da aplicaçao
### C. Administrador geral

# Rotas comuns

### R. Produtos
### R. Produto

### R. Categorias
### R. Categoria



### C. Self-User
### R. Self-User
### U. Self-User
### D. Self-User

### C. Carrinho
### R. Carrinhos
### U. Carrinho
### D. Carrinho

### C. Pedido
### R. Pedidos
### R. Pedido
### U. Pedido
### D. Pedido

### R. ItemsPedido

### C. endereco
### R. enderecos
### R. endereco
### U. endereco
### D. endereco

# Rotas de administrador

### C. Administradores
### R. Usuarios
### U. Self-User
### D. Usuario !== self-User

### C. Categoria
### U. Categoria
### D. Categoria

### C. Produto
### D. Produto
### U. Produto

### C. Propriedade
### R. Propriedade
### D. Propriedade
### U. Propriedade

### R. Pedidos
### R. Pedido
### D. Pedido

### R. ItensPedidos

### C. Promoçao
### R. Promoçoes
### R. Promoçao
### D. Promoçao
### U. Promoçao