@host = http://localhost:3000

## Read All Users
GET {{host}}/users/all

### 
GET {{host}}/users/all
# GET {{urlBase}}/products/importAll

###
GET {{host}}/form/parade-with-us
###
POST {{host}}/api/users
Body: {
  "name": "John Doe",
  "email": "john@example.com",
  "password": "secret"
}

GET {{host}}/orders/{orderId}/items
